version: "3.6"

networks:
    test_network:
        name: action_network

services:
    list_proposals:
        image: ghcr.io/arsulegai/github-updates:v0.1
        container_name: list_proposals
        environment:
            - GITHUB_TOKEN=${GITHUB_TOKEN}
            - CONFIG_FILE=/actions/pull_issues.yaml
            - PR_TEMPLATE_FILE=/assets/html/template/pr-template.html
            - RELEASE_TEMPLATE_FILE=/assets/html/template/release-template.html
            - ISSUE_TEMPLATE_FILE=/assets/html/template/issue-template.html
        volumes:
            - ../actions:/actions
            - ../templates:/templates
            - ../issues:/issues
            - ../trending:/trending
            - ../hyperledger-updates/assets:/assets
        networks:
            - action_network
