name: List projects for 2025

on:
  workflow_dispatch:
  issues:
    types: [ opened ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Clone the repository
        uses: "actions/checkout@v4"
        with:
          submodules: recursive
      - name: Generate the latest project proposals
        run: |
          # Run the docker-compose command
          docker compose -f docker/docker-compose.yaml up --build list_proposals
          exit ${?}
        shell: bash
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
      - name: Create Pull Request with new set of projects
        uses: peter-evans/create-pull-request@v5
        with:
          token: "${{ secrets.GITHUB_TOKEN }}"
          branch-suffix: timestamp
          title: Update Projects
          labels: automerge
          signoff: true
          delete-branch: false
          commit-message: Update Projects
